apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: kube-public
  labels:
    k8s-app: mongodb  
spec:
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  selector:
    k8s-app: mongodb