apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: rocketchat
  name: rocketchat
  namespace: kube-public
spec:
  type: NodePort
  ports:
  - name: rocketchat
    port: 3000
    targetPort: rocketchat
  selector:
    k8s-app: 

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rocketchat
  namespace: kube-public
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: chat.qjw.hj
    http:
      paths:
      - backend:
          serviceName: rocketchat
          servicePort: rocketchat